### ISSUE TITLE
Custom build downloads php file

### ISSUE THREAD

**Issue by karneaud** [Paratron/gamekit#6]
When trying to use the [custom build](http://wearekiss.com/gamekit/en/page/download) the download gives me a corrupted download.php file instead of a archive javascript

**Comment by Paratron** [comment]
What elements did you select? I just tried it and it worked fine.

**Comment by karneaud** [comment]
@Paratron the first 4

**Comment by Paratron** [comment]
Works fine for me - can you send me the download.php file?

**Comment by karneaud** [comment]
@Paratron sure man [here](https://dl.dropboxusercontent.com/u/32676287/download.php)

**Comment by Paratron** [comment]
I have no idea why your browser messed this up, but I am pretty sure that if you rename that file to end with a .zip extension, it will work fine.
